name: Python Application Delivery Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Checkout Repository
    - run: |
        echo "Installing all required dependencies..."
        sudo pip3 install -r requirements.txt

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Deploy to Development Environment
    - run: |
        echo "Deploying to development environment..."
        pm2 delete greetings-app-dev || true
        pm2 start app.py --name greetings-app-dev -- 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Run Tests on Development Environment
    - run: |
        echo "Running tests on development environment..."
        npm install
        npm run greetings_dev

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Deploy to Staging Environment
    - run: |
        echo "Deploying to staging environment..."
        pm2 delete greetings-app-staging || true
        pm2 start app.py --name greetings-app-staging -- 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Run Tests on Staging Environment
    - run: |
        echo "Running tests on staging environment..."
        npm install
        npm run greetings_staging

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Deploy to Pre-production Environment
    - run: |
        echo "Deploying to pre-production environment..."
        pm2 delete greetings-app-preprod || true
        pm2 start app.py --name greetings-app-preprod -- 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Run Tests on Pre-production Environment
    - run: |
        echo "Running tests on pre-production environment..."
        npm install
        npm run greetings_preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Deploy to Production Environment
    - run: |
        echo "Deploying to production environment..."
        pm2 delete greetings-app-prod || true
        pm2 start app.py --name greetings-app-prod -- 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
      name: Run Tests on Production Environment
    - run: |
        echo "Running tests on production environment..."
        npm install
        npm run greetings_prod
