name: Python Application Delivery Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v3.5.2
    - name: Clone python-greetings repository
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: sudo pip3 install -r python-greetings/requirements.txt

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v3.5.2
    - name: Clone python-greetings repository
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Stop existing service
      run: pm2 delete greetings-app-dev || true
      working-directory: ./python-greetings
    - name: Start service on port 7001
      run: pm2 start app.js --name greetings-app-dev -- 7001
      working-directory: ./python-greetings

  deploy-to-staging:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v3.5.2
    - name: Clone python-greetings repository
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Stop existing service
      run: pm2 delete greetings-app-staging || true
      working-directory: ./python-greetings
    - name: Start service on port 7002
      run: pm2 start app.js --name greetings-app-staging -- 7002
      working-directory: ./python-greetings

  deploy-to-preprod:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v3.5.2
    - name: Clone python-greetings repository
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Stop existing service
      run: pm2 delete greetings-app-preprod || true
      working-directory: ./python-greetings
    - name: Start service on port 7003
      run: pm2 start app.js --name greetings-app-preprod -- 7003
      working-directory: ./python-greetings

  deploy-to-prod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v3.5.2
    - name: Clone python-greetings repository
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Stop existing service
      run: pm2 delete greetings-app-prod || true
      working-directory: ./python-greetings
    - name: Start service on port 7004
      run: pm2 start app.js --name greetings-app-prod -- 7004
      working-directory: ./python-greetings
