name: Python Application Delivery Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Environment
      run: |
        mkdir -p /Users/rilyasov/hostedtoolcache/Python
        chmod -R 777 /Users/rilyasov/hostedtoolcache
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Development
      run: echo "Deploying to development environment..."

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
    - name: Run tests in Development
      run: echo "Running tests in development environment..."

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
    - name: Deploy to Staging
      run: echo "Deploying to staging environment..."

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
    - name: Run tests in Staging
      run: echo "Running tests in staging environment..."

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
    - name: Deploy to Pre-Production
      run: echo "Deploying to pre-production environment..."

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
    - name: Run tests in Pre-Production
      run: echo "Running tests in pre-production environment..."

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
    - name: Deploy to Production
      run: echo "Deploying to production environment..."

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
    - name: Run tests in Production
      run: echo "Running tests in production environment..."
