name: Python Application Delivery Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: sudo pip3 install -r python-greetings/requirements.txt
    - run: sudo npm install -g pm2

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: pm2 delete greetings-app-dev || true
      working-directory: ./python-greetings
    - run: pm2 start app.py --name greetings-app-dev -- 7001
      working-directory: ./python-greetings

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/course-js-api-framework
        path: course-js-api-framework
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        sudo chown -R $(whoami) ~/.npm
        sudo npm cache clean --force
        npm install mocha --no-save
        npm install
      working-directory: ./course-js-api-framework
    - run: npm run test-greetings
      working-directory: ./course-js-api-framework

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: pm2 delete greetings-app-staging || true
      working-directory: ./python-greetings
    - run: pm2 start app.py --name greetings-app-staging -- 7002
      working-directory: ./python-greetings

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/course-js-api-framework
        path: course-js-api-framework
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        sudo chown -R $(whoami) ~/.npm
        sudo npm cache clean --force
        npm install mocha --no-save
        npm install
      working-directory: ./course-js-api-framework
    - run: npm run test-greetings
      working-directory: ./course-js-api-framework

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: pm2 delete greetings-app-preprod || true
      working-directory: ./python-greetings
    - run: pm2 start app.py --name greetings-app-preprod -- 7003
      working-directory: ./python-greetings

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/course-js-api-framework
        path: course-js-api-framework
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        sudo chown -R $(whoami) ~/.npm
        sudo npm cache clean --force
        npm install mocha --no-save
        npm install
      working-directory: ./course-js-api-framework
    - run: npm run test-greetings
      working-directory: ./course-js-api-framework

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: pm2 delete greetings-app-prod || true
      working-directory: ./python-greetings
    - run: pm2 start app.py --name greetings-app-prod -- 7004
      working-directory: ./python-greetings

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/course-js-api-framework
        path: course-js-api-framework
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        sudo chown -R $(whoami) ~/.npm
        sudo npm cache clean --force
        npm install mocha --no-save
        npm install
      working-directory: ./course-js-api-framework
    - run: npm run test-greetings
      working-directory: ./course-js-api-framework
